# 6-1. Lab06-1 Softmax Regression (Multinomial Logistic Regression)
#### 2018.09.26 (수)

### Hypothesis
> Softmax function을 이용하여 예측의 결과값을 확률로 변환시켜 준다.
> 
이의 계산 / 예측의 결과값을 모두 합친 것으로, class별 예측값을 나누어주면 끝.
>
이후, 도출된 확률값을 one-hot encoding 을 진행해주면 우리가 원하는  H(x)가 도출!

![lec06_4](../../img/lec06_10.png)
![lec06_4](../../img/lec06_5.png)

### Cost function : cross entropy
$  L = \frac{1}{N}\displaystyle\sum_i D(S(WX_i+b),L_i) $

이때, $D(S,L) = -\displaystyle\sum_i L_ilog(S_i)$

__Gradient descent step__

$-\alpha \Delta L (W_1,W_2)$

![lec06_11](../../img/lec06_11.png)

In [1]:
import tensorflow as tf

/Users/Choi-seonyeol/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [7]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5,],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]
# y_data는 one-hot encoing을 통해 class를 구분하였다.

X = tf.placeholder("float",[None, 4])
Y = tf.placeholder("float",[None, 3])
nb_classes = 3 
# Class의 개수를 잘 지정해주어야 한다. 즉 몇개로 구분되어 지는지.

W = tf.Variable(tf.random_normal([4, nb_classes]), name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]),name = "bias")

# tf.nn.softmax computes softmax activations
# softmax = exp(Logits) / reduce_sum(exp(logits),dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),axis = 1 ))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(optimizer, feed_dict = {X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y: y_data}))
    
    # Test & one-hot encoding
    # 새로운 값을 주어주고, 이를 예측하도록 해보기.
    a = sess.run(hypothesis, feed_dict={X: [[1,11,7,9]]})
    print(a, sess.run(tf.argmax(a,1))) # argmax -> "몇번째에 있는 값이 가장 큰 값인가요? -> max_index 도출"
    print("-"*20)
    # 도출된 a 값은 각각의 arg가 될 확률로 도출된다 !

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b,1)))
    print("-"*20)


    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c,1)))
    print("-"*20)


    all = sess.run(hypothesis, feed_dict={X: [[1,11,7,9],[1, 3, 4, 3],[1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all,1)))

0 2.7933955
200 0.6827578
400 0.57640505
600 0.4869278
800 0.3990815
1000 0.3100286
1200 0.23303121
1400 0.21028756
1600 0.1923558
1800 0.17712557
2000 0.16404395
[[5.34981815e-03 9.94638264e-01 1.19497745e-05]] [1]
--------------------
[[0.86527693 0.11708771 0.01763537]] [0]
--------------------
[[3.1427756e-08 4.1256013e-04 9.9958748e-01]] [2]
--------------------
[[5.34981815e-03 9.94638264e-01 1.19497745e-05]
 [8.65276933e-01 1.17087707e-01 1.76353678e-02]
 [3.14277564e-08 4.12560126e-04 9.99587476e-01]] [1 0 2]
