# lab07-1_Learning rate, Evaluation
#### 2018.09.26(수)

## Training and Test datasets
이 시간부로, 모든 데이터는 Training data 와 Test data로 반드시 나누어 사용한다.<br>
학습에는 Training data만 이용하고, 검증에는 Test data 만 가지고 활용한다.<br>
즉, 학습된 모델에 대해서 검증할때는 처음보는 데이터를 활용해야한다.

In [3]:
import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1],[1, 3, 2],[1, 3, 4],[1, 5, 5],[1, 7, 5],[1, 2, 5],[1, 6, 6],[1, 7, 7]]
y_data = [[0, 0, 1],[0, 0, 1],[0, 0, 1],[0, 1, 0],[0, 1, 0],[0, 1, 0],[1, 0, 0],[1, 0, 0]]

x_test = [[2, 1, 1],[3, 1, 2],[3, 3, 4]]
y_test = [[0, 0, 1],[0, 0, 1],[0, 0, 1]]

In [7]:
X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])

W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost,W,optimizer],
                                     feed_dict = {X: x_data, Y: y_data})
        print(step, cost_val, "\n",W_val)
        
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict = {X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict = {X: x_test, Y: y_test}))


0 3.166142 
 [[-0.9890517  -0.70928216  1.615095  ]
 [-0.15848371  0.4998355   0.12365612]
 [ 1.0272099   0.55762464  0.5185816 ]]
1 1.1283236 
 [[-1.0108453  -0.6998947   1.6275011 ]
 [-0.18806921  0.5247766   0.12830052]
 [ 0.9755329   0.6098516   0.51803166]]
2 1.103297 
 [[-1.0192636  -0.7025076   1.6385324 ]
 [-0.14924563  0.48345646  0.13079706]
 [ 0.9926767   0.59781116  0.5129283 ]]
3 1.0845747 
 [[-1.0351937  -0.6970537   1.6490085 ]
 [-0.15040085  0.48689118  0.12851754]
 [ 0.9703222   0.6283073   0.5047867 ]]
4 1.0703304 
 [[-1.0463663  -0.69677305  1.6599007 ]
 [-0.1274265   0.46215147  0.13028292]
 [ 0.97256666  0.631171    0.4996785 ]]
5 1.0574567 
 [[-1.0605283  -0.69314635  1.6704359 ]
 [-0.12112474  0.4562715   0.12986113]
 [ 0.95873815  0.6516081   0.4930699 ]]
6 1.0454612 
 [[-1.0724721  -0.6918073   1.6810406 ]
 [-0.10415127  0.43824232  0.13091683]
 [ 0.9561442   0.6597243   0.4875477 ]]
7 1.0340286 
 [[-1.0857334  -0.68895054  1.6914452 ]
 [-0.0951012   0.42902818

#### Learning rate값에 따른 학습 진행
두가지 경우
- Overshooting : 발산
- Small learning rate : 더딘 학습진행

![lec07_5](../../img/lec07_5.png)

#### 실험을 진행해보겠습니다. learning_rate를 1.5로 준다면???

In [8]:
X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])

W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1.5).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost,W,optimizer],
                                     feed_dict = {X: x_data, Y: y_data})
        print(step, cost_val, "\n",W_val)
        
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict = {X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict = {X: x_test, Y: y_test}))


0 11.818066 
 [[-1.2579035   0.1499018   1.9189479 ]
 [-2.1098266   0.72860706  0.99695325]
 [-4.265038    1.5609071   1.5934685 ]]
1 16.420557 
 [[-0.8829035   0.6174801   1.0763698 ]
 [ 0.32767344  3.0307727  -3.7427123 ]
 [-1.827538    4.02734    -3.3104644 ]]
2 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
3 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
15 nan 
 [[nan nan nan]
 [nan

결과값이 $\infty$ 하게 되면서, nan값이 도출

#### 두번째 실험을 진행해보겠습니다. learning_rate를 1e-10으로 준다면???

In [9]:

X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])

W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-10).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost,W,optimizer],
                                     feed_dict = {X: x_data, Y: y_data})
        print(step, cost_val, "\n",W_val)
        
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict = {X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict = {X: x_test, Y: y_test}))


0 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
1 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
2 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
3 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
4 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
5 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
6 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.5065799   1.0465151 ]
 [ 0.71529526 -1.6841083   1.2552558 ]]
7 11.250189 
 [[ 1.1523255   1.3558517  -0.20589724]
 [-0.59102607 -0.506579

## Non-normalized input

> 우리가 learning rate를 매우 적절히 줘도 nan값이 나올때가 있다. 그럴때는 normalized가 진행되지 않은 것은 아닌지 확인해보아야 한다.

In [20]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy의 data를 유심히 보면, 세번째 feature는 단위부터가 매우 큰 걸 확인할 수 있다.
이러한 데이터를 그냥 사용하게 되면 문제가 발생
-> 이를 plot으로 그려보면 매우 타원형의 형태가 나오게 된다.(한쪽 방향으로 치우친)
이때, minimize를 위해 학습을 진행하면, 학습이 조금만 어긋나도 튀어나가게 되는 경우가 발생한다.

In [11]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  127319130000.0 
Prediction:
 [[251531.12]
 [508691.53]
 [399693.53]
 [279516.5 ]
 [329819.84]
 [332618.2 ]
 [304687.  ]
 [388544.28]]
1 Cost:  1.3988255e+26 
Prediction:
 [[-8.3428240e+12]
 [-1.6794960e+13]
 [-1.3211989e+13]
 [-9.2615339e+12]
 [-1.0915213e+13]
 [-1.1007084e+13]
 [-1.0088374e+13]
 [-1.2844505e+13]]
2 Cost:  inf 
Prediction:
 [[2.7653416e+20]
 [5.5669160e+20]
 [4.3792922e+20]
 [3.0698604e+20]
 [3.6179946e+20]
 [3.6484466e+20]
 [3.3439276e+20]
 [4.2574846e+20]]
3 Cost:  inf 
Prediction:
 [[-9.1660980e+27]
 [-1.8452295e+28]
 [-1.4515755e+28]
 [-1.0175467e+28]
 [-1.1992332e+28]
 [-1.2093269e+28]
 [-1.1083899e+28]
 [-1.4112007e+28]]
4 Cost:  inf 
Prediction:
 [[3.0382271e+35]
 [6.1162628e+35]
 [4.8114431e+35]
 [3.3727960e+35]
 [3.9750203e+35]
 [4.0084776e+35]
 [3.6739081e+35]
 [4.6776157e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]

문제가 발생하는 것을 확인 할 수 있다.
이는 Normalize가 되지 않아서 발생하는 문제로,
```
xy = MinMaxScaler(xy)
```
를 통해 해결할 수 있다.

In [21]:
from sklearn.preprocessing import MinMaxScaler

xy = MinMaxScaler().fit_transform(xy)


In [22]:
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [23]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  0.7447764 
Prediction:
 [[-0.76111835]
 [ 0.0060225 ]
 [-0.10924425]
 [-0.16440403]
 [-0.26393306]
 [-0.23803449]
 [-0.00173692]
 [ 0.4049295 ]]
1 Cost:  0.7447324 
Prediction:
 [[-0.7610776 ]
 [ 0.00605917]
 [-0.10921366]
 [-0.16438028]
 [-0.2639047 ]
 [-0.23800734]
 [-0.00171997]
 [ 0.4049452 ]]
2 Cost:  0.7446883 
Prediction:
 [[-0.7610369 ]
 [ 0.0060959 ]
 [-0.10918311]
 [-0.16435656]
 [-0.2638764 ]
 [-0.23798007]
 [-0.00170301]
 [ 0.40496093]]
3 Cost:  0.74464417 
Prediction:
 [[-0.76099616]
 [ 0.00613258]
 [-0.10915244]
 [-0.1643328 ]
 [-0.2638481 ]
 [-0.23795292]
 [-0.00168606]
 [ 0.40497667]]
4 Cost:  0.7446001 
Prediction:
 [[-0.76095545]
 [ 0.00616919]
 [-0.10912191]
 [-0.16430905]
 [-0.2638197 ]
 [-0.23792571]
 [-0.00166912]
 [ 0.40499237]]
5 Cost:  0.74455607 
Prediction:
 [[-0.7609147 ]
 [ 0.00620586]
 [-0.10909133]
 [-0.16428536]
 [-0.26379132]
 [-0.23789844]
 [-0.00165216]
 [ 0.40500814]]
6 Cost:  0.74451196 
Prediction:
 [[-0.760874  ]
 [ 0.00624248]
 [-0.10906