# lab07-1 Learning rate, Evaluation using pytorch

In [245]:
import torch
from torch.autograd import Variable
from torch import nn, optim
import numpy as np
import torch.nn.functional as F

In [246]:
x_data = [[1, 2, 1],[1, 3, 2],[1, 3, 4],[1, 5, 5],[1, 7, 5],[1, 2, 5],[1, 6, 6],[1, 7, 7]]
y_data = [[0, 0, 1],[0, 0, 1],[0, 0, 1],[0, 1, 0],[0, 1, 0],[0, 1, 0],[1, 0, 0],[1, 0, 0]]

x_test = [[2, 1, 1],[3, 1, 2],[3, 3, 4]]
y_test = [[0, 0, 1],[0, 0, 1],[0, 0, 1]]

In [247]:
X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

In [248]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(3, 3,bias = True) # 2 in and 1 out
        
    def forward(self, x):
        x = x.view(-1, 3)
        y_pred = self.linear(x)
        F.softmax(y_pred,dim=1)
        return y_pred
    
model = Model()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [249]:
for t in range(10001):    
    optimizer.zero_grad()

    y_pred = model(X)
    cost = criterion(y_pred,torch.max(Y, 1)[1])
    cost.backward()

    optimizer.step()
    if t % 200 == 0:
        print(t,cost.data.numpy(),"\n",list(model.parameters())[0].data.numpy(),list(model.parameters())[1].data.numpy())

0 1.8746886 
 [[-0.03547042  0.31727114  0.35857692]
 [-0.488123    0.13634145  0.32538578]
 [ 0.14158906  0.42832777  0.3866726 ]] [-0.44367993 -0.38319623 -0.10424625]
200 0.88123804 
 [[-0.23530143  0.35226262  0.41702658]
 [-0.47984898  0.23375244  0.5541126 ]
 [ 0.3331462   0.2959253   0.09949615]] [-0.6435105  -0.37492222  0.08731066]
400 0.81042296 
 [[-0.40408772  0.3729268   0.46534777]
 [-0.49986315  0.21025321  0.59062827]
 [ 0.52194643  0.29876038  0.01465949]] [-0.8122963  -0.39493638  0.2761108 ]
600 0.75966495 
 [[-0.54965013  0.3888038   0.5085117 ]
 [-0.51566607  0.2042124   0.608061  ]
 [ 0.68331176  0.28892392 -0.04593743]] [-0.9578589  -0.41073912  0.4374764 ]
800 0.72100914 
 [[-0.67857236  0.4014566   0.54777694]
 [-0.5272222   0.20642616  0.6153979 ]
 [ 0.82379     0.27405733 -0.0925395 ]] [-1.0867805 -0.4222953  0.5779543]
1000 0.69022024 
 [[-0.7951992   0.4117002   0.58422965]
 [-0.53496736  0.21221988  0.6174265 ]
 [ 0.94816196  0.25801983 -0.13102032]] [-1.2

In [250]:
pred = torch.max((F.softmax(model(torch.Tensor(x_test)),dim=1)),1)[1].float()
correct_pred = (pred.numpy() == np.array(y_test).argmax(axis =1))
accuracy = correct_pred.mean()

In [251]:
print(pred.numpy())

[2. 2. 2.]


In [252]:
print(accuracy)

1.0


## Learning Rate  실험
### CASE 1: learning rate  : 10

In [253]:
model = Model()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=10)

In [254]:
for t in range(10001):    
    optimizer.zero_grad()

    y_pred = model(X)
    cost = criterion(y_pred,torch.max(Y, 1)[1])
    cost.backward()

    optimizer.step()
    if t % 200 == 0:
        print("step : ",t,"\tcost : ",cost.data.numpy())

step :  0 	cost :  1.0517436
step :  200 	cost :  80.18485
step :  400 	cost :  71.92984
step :  600 	cost :  53.277527
step :  800 	cost :  1.0728836e-05
step :  1000 	cost :  4.6491623e-06
step :  1200 	cost :  2.9802322e-06
step :  1400 	cost :  2.1457672e-06
step :  1600 	cost :  1.66893e-06
step :  1800 	cost :  1.4305115e-06
step :  2000 	cost :  1.1920929e-06
step :  2200 	cost :  9.536743e-07
step :  2400 	cost :  9.536743e-07
step :  2600 	cost :  7.1525574e-07
step :  2800 	cost :  7.1525574e-07
step :  3000 	cost :  7.1525574e-07
step :  3200 	cost :  7.1525574e-07
step :  3400 	cost :  4.7683716e-07
step :  3600 	cost :  4.7683716e-07
step :  3800 	cost :  4.7683716e-07
step :  4000 	cost :  4.7683716e-07
step :  4200 	cost :  4.7683716e-07
step :  4400 	cost :  4.7683716e-07
step :  4600 	cost :  4.7683716e-07
step :  4800 	cost :  4.7683716e-07
step :  5000 	cost :  4.7683716e-07
step :  5200 	cost :  2.3841858e-07
step :  5400 	cost :  2.3841858e-07
step :  5600 	cost : 

## Learning Rate  실험
### CASE 2: learning rate  : 1e-10

In [259]:
model = Model()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-10)

In [262]:
for t in range(10001):    
    optimizer.zero_grad()

    y_pred = model(X)
    cost = criterion(y_pred,torch.max(Y, 1)[1])
    cost.backward()

    optimizer.step()
    if t % 200 == 0:
        print("step : ",t,"\tcost : ",cost.data.numpy())

step :  0 	cost :  2.260271
step :  200 	cost :  2.260271
step :  400 	cost :  2.260271
step :  600 	cost :  2.260271
step :  800 	cost :  2.260271
step :  1000 	cost :  2.260271
step :  1200 	cost :  2.260271
step :  1400 	cost :  2.260271
step :  1600 	cost :  2.260271
step :  1800 	cost :  2.260271
step :  2000 	cost :  2.260271
step :  2200 	cost :  2.260271
step :  2400 	cost :  2.260271
step :  2600 	cost :  2.260271
step :  2800 	cost :  2.260271
step :  3000 	cost :  2.260271
step :  3200 	cost :  2.260271
step :  3400 	cost :  2.260271
step :  3600 	cost :  2.260271
step :  3800 	cost :  2.260271
step :  4000 	cost :  2.260271
step :  4200 	cost :  2.260271
step :  4400 	cost :  2.260271
step :  4600 	cost :  2.260271
step :  4800 	cost :  2.260271
step :  5000 	cost :  2.260271
step :  5200 	cost :  2.260271
step :  5400 	cost :  2.260271
step :  5600 	cost :  2.260271
step :  5800 	cost :  2.260271
step :  6000 	cost :  2.260271
step :  6200 	cost :  2.260271
step :  6400 	c

## Non-normalized input

> 우리가 learning rate를 매우 적절히 줘도 nan값이 나올때가 있다. 그럴때는 normalized가 진행되지 않은 것은 아닌지 확인해보아야 한다.

In [263]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

In [264]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(4,1,bias = True) # 2 in and 1 out
        
    def forward(self, x):
        x = x.view(-1, 4)
        y_pred = self.linear(x)
        F.softmax(y_pred,dim=1)
        return y_pred
    
model = Model()
criterion = nn.MSELoss(size_average=False)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

/Users/Choi-seonyeol/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [265]:
for t in range(10001):    
    optimizer.zero_grad()

    y_pred = model(X)
    cost = criterion(y_pred,Y)
    cost.backward()

    optimizer.step()
    if t % 200 == 0:
        print("step : ",t,"\tcost : ",cost.data.numpy())

step :  0 	cost :  2044810000000.0
step :  200 	cost :  nan
step :  400 	cost :  nan
step :  600 	cost :  nan
step :  800 	cost :  nan
step :  1000 	cost :  nan
step :  1200 	cost :  nan
step :  1400 	cost :  nan
step :  1600 	cost :  nan
step :  1800 	cost :  nan
step :  2000 	cost :  nan
step :  2200 	cost :  nan
step :  2400 	cost :  nan
step :  2600 	cost :  nan
step :  2800 	cost :  nan
step :  3000 	cost :  nan
step :  3200 	cost :  nan
step :  3400 	cost :  nan
step :  3600 	cost :  nan
step :  3800 	cost :  nan
step :  4000 	cost :  nan
step :  4200 	cost :  nan
step :  4400 	cost :  nan
step :  4600 	cost :  nan
step :  4800 	cost :  nan
step :  5000 	cost :  nan
step :  5200 	cost :  nan
step :  5400 	cost :  nan
step :  5600 	cost :  nan
step :  5800 	cost :  nan
step :  6000 	cost :  nan
step :  6200 	cost :  nan
step :  6400 	cost :  nan
step :  6600 	cost :  nan
step :  6800 	cost :  nan
step :  7000 	cost :  nan
step :  7200 	cost :  nan
step :  7400 	cost :  nan
step : 

문제가 발생하는 것을 확인 할 수 있다.
이는 Normalize가 되지 않아서 발생하는 문제로,
```
xy = MinMaxScaler(xy)
```
를 통해 해결할 수 있다.

In [266]:
from sklearn.preprocessing import MinMaxScaler
xy = MinMaxScaler().fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [267]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

In [268]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(4,1,bias = True) # 2 in and 1 out
        
    def forward(self, x):
        x = x.view(-1, 4)
        y_pred = self.linear(x)
        F.softmax(y_pred,dim=1)
        return y_pred
    
model = Model()
criterion = nn.MSELoss(size_average = False)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

/Users/Choi-seonyeol/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [269]:
for t in range(10001):    
    optimizer.zero_grad()

    y_pred = model(X)
    cost = criterion(y_pred,Y)
    cost.backward()

    optimizer.step()
    if t % 200 == 0:
        print("step : ",t,"\tcost : ",cost.data.numpy())

step :  0 	cost :  8.311975
step :  200 	cost :  0.027330775
step :  400 	cost :  0.026763298
step :  600 	cost :  0.026541281
step :  800 	cost :  0.02634779
step :  1000 	cost :  0.026175305
step :  1200 	cost :  0.026020056
step :  1400 	cost :  0.02587903
step :  1600 	cost :  0.0257498
step :  1800 	cost :  0.025630413
step :  2000 	cost :  0.02551933
step :  2200 	cost :  0.025415236
step :  2400 	cost :  0.025317142
step :  2600 	cost :  0.02522422
step :  2800 	cost :  0.025135778
step :  3000 	cost :  0.025051285
step :  3200 	cost :  0.024970278
step :  3400 	cost :  0.0248924
step :  3600 	cost :  0.024817368
step :  3800 	cost :  0.024744868
step :  4000 	cost :  0.02467478
step :  4200 	cost :  0.024606826
step :  4400 	cost :  0.024540981
step :  4600 	cost :  0.024477035
step :  4800 	cost :  0.024414888
step :  5000 	cost :  0.024354486
step :  5200 	cost :  0.024295727
step :  5400 	cost :  0.024238536
step :  5600 	cost :  0.024182871
step :  5800 	cost :  0.024128618