# lab04-1 multi-variable linear regression 의 TensorFlow 구현

### 2018.09.22(토)

아래 표와 같은 데이터가 있다

x_1|x_2|x_3|Y|
-----|-----|-----|-----|
73|80|75|152
93|88|93|185
89|91|90|180
96|98|100|196
73|66|70|142



## 만약, Matrix를 이용하지 않는다면
__이런식으로 하는 것은 좋지않다! 의 예__

#### Hypothesis
$H(x_1,x_2,x_3) = w_1x_1 + w_2x_2+w_3x_3$

In [126]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]),name = "weight1")
w2 = tf.Variable(tf.random_normal([1]),name = "weight2")
w3 = tf.Variable(tf.random_normal([1]),name = "weight3")
b = tf.Variable(tf.random_normal([1]),name = "bias")

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b


In [127]:
# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [128]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\n Prediction: \n",hy_val)

0 Cost:  251461.6 
 Prediction: 
 [-293.25494 -350.124   -345.9145  -379.0893  -264.67487]
10 Cost:  3.1785283 
 Prediction: 
 [150.34468 183.04752 179.42961 192.9975  141.99998]
20 Cost:  0.87566185 
 Prediction: 
 [151.68799 184.6599  181.01944 194.72902 143.22908]
30 Cost:  0.8747535 
 Prediction: 
 [151.69318 184.66397 181.02452 194.73483 143.23143]
40 Cost:  0.8738987 
 Prediction: 
 [151.69429 184.6632  181.02484 194.73541 143.23009]
50 Cost:  0.8730415 
 Prediction: 
 [151.69542 184.66238 181.02515 194.736   143.22874]
60 Cost:  0.87216985 
 Prediction: 
 [151.69652 184.66158 181.02542 194.73656 143.22737]
70 Cost:  0.8713139 
 Prediction: 
 [151.69765 184.66078 181.02573 194.73714 143.22603]
80 Cost:  0.87045735 
 Prediction: 
 [151.69876 184.65997 181.02602 194.73772 143.22469]
90 Cost:  0.8696116 
 Prediction: 
 [151.69984 184.65918 181.0263  194.73828 143.22334]
100 Cost:  0.8687625 
 Prediction: 
 [151.70096 184.65839 181.02661 194.73886 143.222  ]
110 Cost:  0.8679161 
 Pr

## 우리는 이제 Matrix를 이용할 것이다.
$\matrix{(x_1 & x_2 & x_3)} *  \begin{pmatrix} w_1 \\ w_2 \\ w_3 \end{pmatrix} = \matrix{(x_1w_1 + x_2w_2+x_3w_3)}$

$H(X) = XW$

In [120]:
x_data = [[73., 80., 75.],
         [93., 88., 93.],
          [89., 91., 90.],
         [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3]) # 데이터의 개수(N)가 아직 미정인 것이므로, None 값을 넣어준다 ( 즉, feed_dict 에 의해 결정)
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [125]:
x_data

[[73.0, 80.0, 75.0],
 [93.0, 88.0, 93.0],
 [89.0, 91.0, 90.0],
 [96.0, 98.0, 100.0],
 [73.0, 66.0, 70.0]]

In [121]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\n Prediction: \n",hy_val)

0 Cost:  72046.33 
 Prediction: 
 [[ -84.69282]
 [-103.04279]
 [-100.95007]
 [-109.78126]
 [ -78.91717]]
10 Cost:  3.6610878 
 Prediction: 
 [[152.73987]
 [182.34532]
 [180.24164]
 [196.42992]
 [138.76465]]
20 Cost:  2.9872453 
 Prediction: 
 [[153.45207]
 [183.21307]
 [181.09055]
 [197.35481]
 [139.42905]]
30 Cost:  2.9730096 
 Prediction: 
 [[153.44807]
 [183.21996]
 [181.09126]
 [197.35605]
 [139.43683]]
40 Cost:  2.9588826 
 Prediction: 
 [[153.44193]
 [183.2242 ]
 [181.08942]
 [197.35449]
 [139.4426 ]]
50 Cost:  2.9447982 
 Prediction: 
 [[153.43579]
 [183.22845]
 [181.08759]
 [197.35294]
 [139.44836]]
60 Cost:  2.930783 
 Prediction: 
 [[153.42964]
 [183.23268]
 [181.08571]
 [197.35136]
 [139.45409]]
70 Cost:  2.916858 
 Prediction: 
 [[153.42352]
 [183.23688]
 [181.08386]
 [197.3498 ]
 [139.45981]]
80 Cost:  2.903035 
 Prediction: 
 [[153.41743]
 [183.24107]
 [181.08202]
 [197.34825]
 [139.4655 ]]
90 Cost:  2.889239 
 Prediction: 
 [[153.41135]
 [183.24527]
 [181.08018]
 [197.34