In [1]:
import torch
from torch.autograd import Variable
from torch import nn, optim
import numpy as np
import torch.nn.functional as F

In [34]:
x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype = np.float32)
y_data = np.array([[0],[1],[1],[0]], dtype = np.float32)

### 만약에, Logistic Regression 으로 XOR을 해보려고 하면??

In [46]:
X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))


class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(2, 1,bias = True) # 2 in and 1 out
        
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred


model = Model()
criterion = torch.nn.BCELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [47]:
for t in range(10001):
    y_pred = model(X)
    cost = criterion(y_pred,Y)
    
    optimizer.zero_grad()
    cost.backward(retain_graph=True)
    optimizer.step()
    if t % 20 == 0:
        print(t, "\ncost : ",cost.data.numpy(), "\nweight : \n",model.linear.weight.data.numpy(), model.linear.bias.data.numpy())


0 
cost :  3.3102906 
weight : 
 [[-0.1750368  -0.64967406]] [-0.5862413]
20 
cost :  3.083909 
weight : 
 [[-0.0892744  -0.54461277]] [-0.42553356]
40 
cost :  2.9493704 
weight : 
 [[-0.02536957 -0.46065453]] [-0.30280298]
60 
cost :  2.872867 
weight : 
 [[ 0.02055571 -0.39465988]] [-0.21114844]
80 
cost :  2.83045 
weight : 
 [[ 0.05251059 -0.3430677 ]] [-0.1436942]
100 
cost :  2.807177 
weight : 
 [[ 0.07399172 -0.30261686]] [-0.09452138]
120 
cost :  2.7943892 
weight : 
 [[ 0.08779312 -0.27061972]] [-0.05891591]
140 
cost :  2.7872715 
weight : 
 [[ 0.0960458 -0.24498  ]] [-0.03327791]
160 
cost :  2.7832074 
weight : 
 [[ 0.10033491 -0.22411057]] [-0.01492029]
180 
cost :  2.7807913 
weight : 
 [[ 0.10182352 -0.20682818]] [-0.00186189]
200 
cost :  2.7792726 
weight : 
 [[ 0.10135821 -0.1922577 ]] [0.00734819]
220 
cost :  2.778251 
weight : 
 [[ 0.09955207 -0.1797541 ]] [0.01376854]
240 
cost :  2.7775118 
weight : 
 [[ 0.0968473  -0.16884255]] [0.01816986]
260 
cost :  2.776

In [48]:

predicted = (model(X).data > 0.5).float()
accuracy = (predicted == Y.data).float().mean()
print("Hypotheis : \n",y_pred.detach().numpy(), \
      "\nCorrect : \n",predicted.detach().numpy(),\
      "\nAccuracy : ",accuracy.numpy())

Hypotheis : 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
Correct : 
 [[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy :  0.5


학습이 잘 안된다! 아무리 많이 돌려도, 0.5를 넘을 수 없다. -> 이론적으로, XOR은 logistic Regression 으로 불가능하다.

### Neural Net을 이용한다면?

In [58]:
x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype = np.float32)
y_data = np.array([[0],[1],[1],[0]], dtype = np.float32)
X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))


In [62]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.l1 = torch.nn.Linear(2, 2,bias = True)
        self.l2 = torch.nn.Linear(2, 1,bias = True)
    def forward(self, x):
        y1 = torch.sigmoid(self.l1(x))
        y2 = torch.sigmoid(self.l2(y1))
        return y2


model = Model()
criterion = torch.nn.BCELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [63]:
for t in range(10001):
    y_pred = model(X)
    cost = criterion(y_pred,Y)
    
    optimizer.zero_grad()
    cost.backward(retain_graph=True)
    optimizer.step()
    if t % 20 == 0:
        print(t, "\ncost : ",cost.data.numpy())


0 
cost :  3.0353146
20 
cost :  2.7723446
40 
cost :  2.7720046
60 
cost :  2.7719755
80 
cost :  2.7719445
100 
cost :  2.771912
120 
cost :  2.771878
140 
cost :  2.7718415
160 
cost :  2.7718027
180 
cost :  2.7717612
200 
cost :  2.7717175
220 
cost :  2.7716703
240 
cost :  2.7716208
260 
cost :  2.771567
280 
cost :  2.7715096
300 
cost :  2.7714481
320 
cost :  2.771382
340 
cost :  2.7713113
360 
cost :  2.7712348
380 
cost :  2.7711518
400 
cost :  2.7710624
420 
cost :  2.770965
440 
cost :  2.7708597
460 
cost :  2.7707448
480 
cost :  2.7706203
500 
cost :  2.7704835
520 
cost :  2.7703333
540 
cost :  2.7701688
560 
cost :  2.7699873
580 
cost :  2.7697873
600 
cost :  2.769565
620 
cost :  2.7693186
640 
cost :  2.769044
660 
cost :  2.7687364
680 
cost :  2.7683914
700 
cost :  2.7680025
720 
cost :  2.7675622
740 
cost :  2.767062
760 
cost :  2.766491
780 
cost :  2.7658358
800 
cost :  2.7650807
820 
cost :  2.7642052
840 
cost :  2.7631848
860 
cost :  2.7619884
880

In [64]:

predicted = (model(X).data > 0.5).float()
accuracy = (predicted == Y.data).float().mean()
print("Hypotheis : \n",y_pred.detach().numpy(), \
      "\nCorrect : \n",predicted.detach().numpy(),\
      "\nAccuracy : ",accuracy.numpy())

Hypotheis : 
 [[0.00268321]
 [0.99752504]
 [0.996338  ]
 [0.00230685]] 
Correct : 
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy :  1.0
